console.log(Math.random());
console.log(Math.PI);
console.log(Math.sqrt(16)); 
console.log(Math.pow(2, 3));
console.log(Math.max(10, 20, 30));
console.log(Math.min(10, 20, 30));
console.log(Math.floor(4.7));
console.log(Math.ceil(4.1));
console.log(Math.round(4.5));
console.log(Math.abs(-5));